//Generated by TurboLink CodeGenerator, do not edit!
#include "SEcsstream/EcsStreamMessage.h"
#include "TurboLinkGrpcContext.h"
#include "ecs_stream.pb.h"

void GRPC_TO_TURBOLINK(const ::ecsstream::TxMetadata* in, FGrpcEcsstreamTxMetadata* out);
void TURBOLINK_TO_GRPC(const FGrpcEcsstreamTxMetadata* in, ::ecsstream::TxMetadata* out);

void GRPC_TO_TURBOLINK(const ::ecsstream::ECSEvent* in, FGrpcEcsstreamECSEvent* out);
void TURBOLINK_TO_GRPC(const FGrpcEcsstreamECSEvent* in, ::ecsstream::ECSEvent* out);

void GRPC_TO_TURBOLINK(const ::ecsstream::ECSStreamBlockBundleRequest* in, FGrpcEcsstreamECSStreamBlockBundleRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcEcsstreamECSStreamBlockBundleRequest* in, ::ecsstream::ECSStreamBlockBundleRequest* out);

void GRPC_TO_TURBOLINK(const ::ecsstream::ECSStreamBlockBundleReply* in, FGrpcEcsstreamECSStreamBlockBundleReply* out);
void TURBOLINK_TO_GRPC(const FGrpcEcsstreamECSStreamBlockBundleReply* in, ::ecsstream::ECSStreamBlockBundleReply* out);

typedef grpc::ClientAsyncReader<::ecsstream::ECSStreamBlockBundleReply> ECSStreamService_SubscribeToStreamLatest_ReaderWriter;
