//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SEcssnapshot/EcsSnapshotService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "ecs_snapshot.grpc.pb.h"
#include "EcsSnapshotService_Private.generated.h"

class UECSStateSnapshotService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::ecssnapshot::ECSStateSnapshotService::Stub> Stub;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& Result, const FGrpcEcssnapshotECSStateReply& Response);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestLambda Lambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestStreamLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& Result, const FGrpcEcssnapshotECSStateReply& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestStreamLambda Lambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestStreamV2LambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& Result, const FGrpcEcssnapshotECSStateReplyV2& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestStreamV2Lambda Lambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestStreamPrunedLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& Result, const FGrpcEcssnapshotECSStateReply& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestStreamPrunedLambda Lambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestStreamPrunedV2LambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& Result, const FGrpcEcssnapshotECSStateReplyV2& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestStreamPrunedV2Lambda Lambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateBlockLatestLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& Result, const FGrpcEcssnapshotECSStateBlockReply& Response);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateBlockLatestLambda Lambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateAtBlockLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& Result, const FGrpcEcssnapshotECSStateReply& Response);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateAtBlockLambda Lambda;
};

UCLASS()
class UECSStateSnapshotServiceGetWorldsLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& Result, const FGrpcEcssnapshotWorlds& Response);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetWorldsLambda Lambda;
};

