//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SEcssnapshot/EcsSnapshotMessage.h"
#include "EcsSnapshotClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnECSStateSnapshotServiceGetStateLatestResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcEcssnapshotECSStateReply&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnECSStateSnapshotServiceGetStateLatestStreamResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcEcssnapshotECSStateReply&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnECSStateSnapshotServiceGetStateLatestStreamV2Response, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcEcssnapshotECSStateReplyV2&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnECSStateSnapshotServiceGetStateLatestStreamPrunedResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcEcssnapshotECSStateReply&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnECSStateSnapshotServiceGetStateLatestStreamPrunedV2Response, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcEcssnapshotECSStateReplyV2&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnECSStateSnapshotServiceGetStateBlockLatestResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcEcssnapshotECSStateBlockReply&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnECSStateSnapshotServiceGetStateAtBlockResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcEcssnapshotECSStateReply&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnECSStateSnapshotServiceGetWorldsResponse, FGrpcContextHandle, Handle, const FGrpcResult&, Result, const FGrpcEcssnapshotWorlds&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UECSStateSnapshotServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnECSStateSnapshotServiceGetStateLatestResponse OnGetStateLatestResponse;

	UPROPERTY(BlueprintAssignable)
	FOnECSStateSnapshotServiceGetStateLatestStreamResponse OnGetStateLatestStreamResponse;

	UPROPERTY(BlueprintAssignable)
	FOnECSStateSnapshotServiceGetStateLatestStreamV2Response OnGetStateLatestStreamV2Response;

	UPROPERTY(BlueprintAssignable)
	FOnECSStateSnapshotServiceGetStateLatestStreamPrunedResponse OnGetStateLatestStreamPrunedResponse;

	UPROPERTY(BlueprintAssignable)
	FOnECSStateSnapshotServiceGetStateLatestStreamPrunedV2Response OnGetStateLatestStreamPrunedV2Response;

	UPROPERTY(BlueprintAssignable)
	FOnECSStateSnapshotServiceGetStateBlockLatestResponse OnGetStateBlockLatestResponse;

	UPROPERTY(BlueprintAssignable)
	FOnECSStateSnapshotServiceGetStateAtBlockResponse OnGetStateAtBlockResponse;

	UPROPERTY(BlueprintAssignable)
	FOnECSStateSnapshotServiceGetWorldsResponse OnGetWorldsResponse;

public:
	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetStateLatest();

	UFUNCTION(BlueprintCallable)
	void GetStateLatest(FGrpcContextHandle Handle, const FGrpcEcssnapshotECSStateRequestLatest& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetStateLatestStream();

	UFUNCTION(BlueprintCallable)
	void GetStateLatestStream(FGrpcContextHandle Handle, const FGrpcEcssnapshotECSStateRequestLatestStream& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetStateLatestStreamV2();

	UFUNCTION(BlueprintCallable)
	void GetStateLatestStreamV2(FGrpcContextHandle Handle, const FGrpcEcssnapshotECSStateRequestLatestStream& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetStateLatestStreamPruned();

	UFUNCTION(BlueprintCallable)
	void GetStateLatestStreamPruned(FGrpcContextHandle Handle, const FGrpcEcssnapshotECSStateRequestLatestStreamPruned& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetStateLatestStreamPrunedV2();

	UFUNCTION(BlueprintCallable)
	void GetStateLatestStreamPrunedV2(FGrpcContextHandle Handle, const FGrpcEcssnapshotECSStateRequestLatestStreamPruned& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetStateBlockLatest();

	UFUNCTION(BlueprintCallable)
	void GetStateBlockLatest(FGrpcContextHandle Handle, const FGrpcEcssnapshotECSStateBlockRequestLatest& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetStateAtBlock();

	UFUNCTION(BlueprintCallable)
	void GetStateAtBlock(FGrpcContextHandle Handle, const FGrpcEcssnapshotECSStateRequestAtBlock& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetWorlds();

	UFUNCTION(BlueprintCallable)
	void GetWorlds(FGrpcContextHandle Handle, const FGrpcEcssnapshotWorldsRequest& Request);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable)
	void TryCancel(FGrpcContextHandle Handle);
};

