//Generated by TurboLink CodeGenerator, do not edit!
#include "EcsRelayService_Private.h"

void UECSRelayServiceAuthenticateLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelayIdentity& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnAuthenticateResponse.RemoveDynamic(this, &UECSRelayServiceAuthenticateLambdaWrapper::OnResponse);
}

void UECSRelayServiceRevokeLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelayIdentity& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnRevokeResponse.RemoveDynamic(this, &UECSRelayServiceRevokeLambdaWrapper::OnResponse);
}

void UECSRelayServicePingLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelayIdentity& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnPingResponse.RemoveDynamic(this, &UECSRelayServicePingLambdaWrapper::OnResponse);
}

void UECSRelayServiceCountAuthenticatedLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelayCountIdentitiesResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnCountAuthenticatedResponse.RemoveDynamic(this, &UECSRelayServiceCountAuthenticatedLambdaWrapper::OnResponse);
}

void UECSRelayServiceCountConnectedLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelayCountIdentitiesResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnCountConnectedResponse.RemoveDynamic(this, &UECSRelayServiceCountConnectedLambdaWrapper::OnResponse);
}

void UECSRelayServiceSubscribeLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelaySubscription& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnSubscribeResponse.RemoveDynamic(this, &UECSRelayServiceSubscribeLambdaWrapper::OnResponse);
}

void UECSRelayServiceUnsubscribeLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelaySubscription& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnUnsubscribeResponse.RemoveDynamic(this, &UECSRelayServiceUnsubscribeLambdaWrapper::OnResponse);
}

void UECSRelayServiceOpenStreamLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelayMessage& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
}

void UECSRelayServiceOpenStreamLambdaWrapper::OnContextStateChanged(FGrpcContextHandle _Handle, EGrpcContextState NewState)
{
	if (_Handle != this->Handle) return;
	if (NewState == EGrpcContextState::Done)
	{
		InnerClient->OnOpenStreamResponse.RemoveDynamic(this, &UECSRelayServiceOpenStreamLambdaWrapper::OnResponse);
		InnerClient->OnContextStateChange.RemoveDynamic(this, &UECSRelayServiceOpenStreamLambdaWrapper::OnContextStateChanged);
	}
}

void UECSRelayServicePushLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelayPushResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnPushResponse.RemoveDynamic(this, &UECSRelayServicePushLambdaWrapper::OnResponse);
}

void UECSRelayServiceMinBalanceForPushLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& Result, const FGrpcEcsrelayBalanceResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(Result, Response);
	InnerClient->OnMinBalanceForPushResponse.RemoveDynamic(this, &UECSRelayServiceMinBalanceForPushLambdaWrapper::OnResponse);
}

