//Generated by TurboLink CodeGenerator, do not edit!
#include "SEcsrelay/EcsRelayMessage.h"

FGrpcEcsrelaySubscriptionRequest UGrpcEcsrelaySubscriptionRequestHelperLibrary::MakeSubscriptionRequest( 
    FGrpcEcsrelaySignature Signature, FGrpcEcsrelaySubscription Subscription 
)
{
    FGrpcEcsrelaySubscriptionRequest SubscriptionRequest;
    SubscriptionRequest.Signature = Signature;
    SubscriptionRequest.Subscription = MakeShareable(new FGrpcEcsrelaySubscription(Subscription));

    return SubscriptionRequest;
}

void UGrpcEcsrelaySubscriptionRequestHelperLibrary::BreakSubscriptionRequest(const FGrpcEcsrelaySubscriptionRequest& SubscriptionRequest,  
    FGrpcEcsrelaySignature& Signature, FGrpcEcsrelaySubscription& Subscription 
)
{
    Signature = SubscriptionRequest.Signature;
    Subscription = *(SubscriptionRequest.Subscription.Get());
}

