//Generated by TurboLink CodeGenerator, do not edit!
#include "SGreeter/GreeterMessage.h"
#include "TurboLinkGrpcContext.h"
#include "greeter.pb.h"

void GRPC_TO_TURBOLINK(const ::Greeter::HelloRequest* in, FGrpcGreeterHelloRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGreeterHelloRequest* in, ::Greeter::HelloRequest* out);

void GRPC_TO_TURBOLINK(const ::Greeter::HelloResponse* in, FGrpcGreeterHelloResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcGreeterHelloResponse* in, ::Greeter::HelloResponse* out);

void GRPC_TO_TURBOLINK(const ::Greeter::TicktokRequest* in, FGrpcGreeterTicktokRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGreeterTicktokRequest* in, ::Greeter::TicktokRequest* out);

void GRPC_TO_TURBOLINK(const ::Greeter::WatchRequest* in, FGrpcGreeterWatchRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcGreeterWatchRequest* in, ::Greeter::WatchRequest* out);

void GRPC_TO_TURBOLINK(const ::Greeter::NowResponse* in, FGrpcGreeterNowResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcGreeterNowResponse* in, ::Greeter::NowResponse* out);

typedef grpc::ClientAsyncResponseReader<::Greeter::HelloResponse> GreeterService_Hello_ReaderWriter;
typedef grpc::ClientAsyncReader<::Greeter::NowResponse> TimeService_Ticktok_ReaderWriter;
typedef grpc::ClientAsyncReaderWriter<::Greeter::WatchRequest, ::Greeter::NowResponse> TimeService_Watch_ReaderWriter;
